// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_unused_packages/test/analyze_dependencies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_unused_packages/domain/repository/dependency_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DependencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDependencyRepository extends _i1.Mock
    implements _i2.DependencyRepository {
  MockDependencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Set<String>> getAllDependencies() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDependencies, []),
            returnValue: _i3.Future<Set<String>>.value(<String>{}),
          )
          as _i3.Future<Set<String>>);

  @override
  _i3.Future<Set<String>> getUsedDependencies() =>
      (super.noSuchMethod(
            Invocation.method(#getUsedDependencies, []),
            returnValue: _i3.Future<Set<String>>.value(<String>{}),
          )
          as _i3.Future<Set<String>>);

  @override
  _i3.Future<void> removeUnusedDependencies(Set<String>? unusedDependencies) =>
      (super.noSuchMethod(
            Invocation.method(#removeUnusedDependencies, [unusedDependencies]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
