name: flutter_unused_packages
description: “A CLI tool to scan, detect and remove unused dependencies in Flutter projects, improving code organization.”
version: 1.0.0
repository: https://github.com/ErikMendesRC/flutter_unused_packages
homepage: https://github.com/ErikMendesRC/flutter_unused_packages
issue_tracker: https://github.com/ErikMendesRC/flutter_unused_packages/issues
documentation: https://github.com/ErikMendesRC/flutter_unused_packages/wiki

environment:
  sdk: ">=3.7.0 <4.0.0"

executables:
  flutter_unused_packages: flutter_unused_packages

dependencies:
  analyzer: ^7.3.0
  args: ^2.6.0
  glob: ^2.1.3
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^2.0.0
  test: ^1.24.0
  mockito: ^5.4.5

platforms:
  linux:
  macos:
  windows:

topics:
  - flutter
  - cli
  - analysis
  - dependencies
  - cleanup
  - optimization
  - best-practices

screenshots:
  - description: "Detect and remove unused dependencies in your Flutter project"
    path: assets/logo.jpg

funding:
  - https://github.com/sponsors/ErikMendesRC